In [168]:
import pandas as pd
import numpy as np
import joblib

In [169]:
with open('regression_model.joblib', 'rb') as f:
    regressor = joblib.load(f)
with open('venue_encoder.joblib', 'rb') as f:
    venue_encoder = joblib.load(f)
with open('team_encoder.joblib', 'rb') as f:
    team_encoder = joblib.load(f)

In [170]:
regressor

Lasso()

In [171]:
venue_encoder

LabelEncoder()

In [172]:
#read test data
test_case = pd.read_csv('inputFile2.csv')
test_case

venue  innings    batting_team    bowling_team  \
0  MA Chidambaram Stadium        1  Mumbai Indians  Delhi Capitals   

                                           batsmen  \
0  Rohit Sharma, Quinton de Kock, Suryakumar Yadav   

                                             bowlers  
0  Marcus Stoinis, Ravichandran Ashwin, Kagiso Ra...

In [173]:
 #encode venue, batting team and bowling teams
test_case['venue'] = venue_encoder.transform(test_case['venue'])
test_case['batting_team'] = team_encoder.transform(test_case['batting_team'])
test_case['bowling_team'] = team_encoder.transform(test_case['bowling_team'])
test_case

venue  innings  batting_team  bowling_team  \
0     16        1             6             2   

                                           batsmen  \
0  Rohit Sharma, Quinton de Kock, Suryakumar Yadav   

                                             bowlers  
0  Marcus Stoinis, Ravichandran Ashwin, Kagiso Ra...

In [174]:
 #make sure that the order of columns is same as tha fed to model
test_case = test_case[['venue', 'innings', 'batting_team', 'bowling_team']]
test_case

venue  innings  batting_team  bowling_team
0     16        1             6             2

In [175]:
 #convert input test case int numpy array
testArray = test_case.to_numpy()
testArray

array([[16,  1,  6,  2]], dtype=int64)

In [176]:
#one hot encode venue, batting team and bowling team
test_case = np.concatenate((np.eye(42)[testArray[:,0]], np.eye(2)[testArray[:,1]-1], np.eye(15)[testArray[:,2]], np.eye(15)[testArray[:,3]],), axis = 1)
test_case

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [177]:
regressor.predict(test_case)

array([45.73188406])