In [288]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Lasso
from sklearn.preprocessing import LabelEncoder
import joblib

In [289]:
#read data from unzipped file
data = pd.read_csv('Preprocessed.csv')
data

venue  innings  \
0                            M.Chinnaswamy Stadium        1   
1                            M.Chinnaswamy Stadium        2   
2     Punjab Cricket Association IS Bindra Stadium        1   
3     Punjab Cricket Association IS Bindra Stadium        2   
4                             Arun Jaitley Stadium        1   
...                                            ...      ...   
1651                              Wankhede Stadium        2   
1652                              Wankhede Stadium        1   
1653                              Wankhede Stadium        2   
1654                        MA Chidambaram Stadium        1   
1655                        MA Chidambaram Stadium        2   

                     batting_team                 bowling_team  total_runs  
0           Kolkata Knight Riders  Royal Challengers Bangalore          61  
1     Royal Challengers Bangalore        Kolkata Knight Riders          26  
2             Chennai Super Kings                 Punjab Kings          53  
3                    Punjab Kings          Chennai Super Kings          56  
4                Rajasthan Royals               Delhi Capitals          40  
...                           ...                          ...         ...  
1651               Delhi Capitals                 Punjab Kings          62  
1652          Chennai Super Kings             Rajasthan Royals          46  
1653             Rajasthan Royals          Chennai Super Kings          45  
1654               Mumbai Indians               Delhi Capitals          55  
1655               Delhi Capitals               Mumbai Indians          39  

[1656 rows x 5 columns]

In [290]:
venue_encoder = LabelEncoder()
team_encoder = LabelEncoder()

In [291]:
data['venue'] = venue_encoder.fit_transform(data['venue'])
data

venue  innings                 batting_team  \
0        15        1        Kolkata Knight Riders   
1        15        2  Royal Challengers Bangalore   
2        22        1          Chennai Super Kings   
3        22        2                 Punjab Kings   
4         0        1             Rajasthan Royals   
...     ...      ...                          ...   
1651     34        2               Delhi Capitals   
1652     34        1          Chennai Super Kings   
1653     34        2             Rajasthan Royals   
1654     16        1               Mumbai Indians   
1655     16        2               Delhi Capitals   

                     bowling_team  total_runs  
0     Royal Challengers Bangalore          61  
1           Kolkata Knight Riders          26  
2                    Punjab Kings          53  
3             Chennai Super Kings          56  
4                  Delhi Capitals          40  
...                           ...         ...  
1651                 Punjab Kings          62  
1652             Rajasthan Royals          46  
1653          Chennai Super Kings          45  
1654               Delhi Capitals          55  
1655               Mumbai Indians          39  

[1656 rows x 5 columns]

In [292]:
data['batting_team'] = team_encoder.fit_transform(data['batting_team'])
data['bowling_team'] = team_encoder.fit_transform(data['bowling_team'])
data

venue  innings  batting_team  bowling_team  total_runs
0        15        1             5            12          61
1        15        2            12             5          26
2        22        1             0             8          53
3        22        2             8             0          56
4         0        1             9             2          40
...     ...      ...           ...           ...         ...
1651     34        2             2             8          62
1652     34        1             0             9          46
1653     34        2             9             0          45
1654     16        1             6             2          55
1655     16        2             2             6          39

[1656 rows x 5 columns]

In [293]:
#get data in a numpy Array
anArray = data.to_numpy()
anArray

array([[15,  1,  5, 12, 61],
       [15,  2, 12,  5, 26],
       [22,  1,  0,  8, 53],
       ...,
       [34,  2,  9,  0, 45],
       [16,  1,  6,  2, 55],
       [16,  2,  2,  6, 39]], dtype=int64)

In [294]:
#get independent and target variables
X,y = anArray[:,:3], anArray[:,4]
X

array([[15,  1,  5],
       [15,  2, 12],
       [22,  1,  0],
       ...,
       [34,  2,  9],
       [16,  1,  6],
       [16,  2,  2]], dtype=int64)

In [295]:
y

array([61, 26, 53, ..., 45, 55, 39], dtype=int64)

In [296]:
X = np.concatenate((np.eye(42)[anArray[:,0]], np.eye(2)[anArray[:,1]-1], np.eye(15)[anArray[:,2]], np.eye(15)[anArray[:,3]],), axis = 1)
X

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [297]:
X_train , X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25)

In [298]:
#fit a linear regressor
linearRegressor = LinearRegression()

In [299]:
#train the model
linearRegressor.fit(X_train, y_train)


LinearRegression()

In [300]:
#save the model and supporting label encoders
joblib.dump(linearRegressor, 'regression_model.joblib')
joblib.dump(venue_encoder, 'venue_encoder.joblib')
joblib.dump(team_encoder, 'team_encoder.joblib')

print(linearRegressor.score(X_test,y_test))

-0.001990004471174478


In [301]:
y_predict = linearRegressor.predict(X_test)

In [302]:
from sklearn import metrics
print(metrics.mean_squared_error(y_test,y_predict))

138.29408212560386
